# pinned conda environment (linux) exported with
# "conda env export > environment_pinned_py3.yml --no-builds"
name: qa4sm-reader
channels:
- defaults
dependencies:
- _libgcc_mutex=0.1
- asn1crypto=0.24.0
- blas=1.0
- bzip2=1.0.8
- ca-certificates=2019.5.15
- cartopy=0.17.0
- certifi=2019.6.16
- cffi=1.12.3
- cftime=1.0.3.4
- chardet=3.0.4
- colorcet=2.0.1
- cryptography=2.7
- curl=7.65.2
- cycler=0.10.0
- dbus=1.13.6
- expat=2.2.6
- fontconfig=2.13.0
- freetype=2.9.1
- geos=3.7.1
- glib=2.56.2
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- hdf4=4.2.13
- hdf5=1.10.4
- icu=58.2
- idna=2.8
- intel-openmp=2019.4
- jpeg=9b
- kiwisolver=1.1.0
- krb5=1.16.1
- libcurl=7.65.2
- libedit=3.1.20181209
- libffi=3.2.1
- libgcc-ng=9.1.0
- libgfortran-ng=7.3.0
- libnetcdf=4.6.1
- libpng=1.6.37
- libssh2=1.8.2
- libstdcxx-ng=9.1.0
- libtiff=4.0.10
- libuuid=1.0.3
- libxcb=1.13
- libxml2=2.9.9
- libxslt=1.1.33
- lxml=4.3.4
- matplotlib=3.1.0
- mkl=2019.4
- mkl-service=2.0.2
- mkl_fft=1.0.12
- mkl_random=1.0.2
- ncurses=6.1
- netcdf4=1.4.2
- numpy=1.16.4
- numpy-base=1.16.4
- olefile=0.46
- openssl=1.1.1c
- owslib=0.18.0
- pandas=0.25.0
- param=1.9.1
- patsy=0.5.1
- pcre=8.43
- pillow=6.1.0
- pip=19.1.1
- proj4=5.2.0
- pycparser=2.19
- pyct=0.4.6
- pyepsg=0.4.0
- pykdtree=1.3.1
- pyopenssl=19.0.0
- pyparsing=2.4.0
- pyproj=1.9.6
- pyqt=5.9.2
- pyshp=2.1.0
- pysocks=1.7.0
- python=3.6.9
- python-dateutil=2.8.0
- pytz=2019.1
- pyyaml=5.1.1
- qt=5.9.7
- readline=7.0
- requests=2.22.0
- scipy=1.3.0
- seaborn=0.9.0
- setuptools=41.0.1
- shapely=1.6.4
- sip=4.19.8
- six=1.12.0
- sqlite=3.29.0
- statsmodels=0.10.1
- tk=8.6.8
- tornado=6.0.3
- urllib3=1.24.2
- wheel=0.33.4
- xarray=0.12.1
- xz=5.2.4
- yaml=0.1.7
- zlib=1.2.11
- zstd=1.3.7

